### ISSUE TITLE
Cloud Formation factory-initialization-stack Failure

### ISSUE THREAD

**Issue by VictorRaim** [awslabs/aws-service-catalog-factory#100]
Playing the workshop I'm getting stopped by the following error during the deployment of the cloud formation _factory-initialization-stack_ :

```
2019-11-05 17:44:43 UTC+0100 | StartInstall | Failed to create resource. CloudWatch Log Stream: 2019/11/05/[$LATEST]a2a54f2f7af445669994cfddfb9fbe8c
```

Stacked was deployed following guidelines and with AdministratorAccess account (not the root one)

**Comment by eamonnfaherty** [comment]
Thanks for raising this issue and sorry you have hit this issue.

Were you trying to install this into a fresh account?

Would you be able to share the output from the AWS CodeBuild project: servicecatalog-product-puppet-initialiser

**Comment by VictorRaim** [comment]
Thank you for the quick response.

The stack failing is the following : https://service-catalog-tools.s3.eu-west-2.amazonaws.com/factory/latest/servicecatalog-factory-initialiser.template.yaml

The install is not from a fresh account.

You will find attached the CodeBuild logs from _servicecatalog-product-factory-initialiser
[servicecatalog-product-factory-initialiser_codebuild_Logs.txt](https://github.com/awslabs/aws-service-catalog-factory/files/3813787/servicecatalog-product-factory-initialiser_codebuild_Logs.txt)
_

**Comment by eamonnfaherty** [comment]
Thanks for the report.  I have identified the issue and will get a release out to fix this.  Should be this morning.

**Comment by eamonnfaherty** [comment]
Sorry for this issue.

There was a conflict between the dependencies of dependencies.

This has now been resolved.
