### ISSUE TITLE
Gracefully recover from an erroneous Portfolio Association

### ISSUE THREAD

**Issue by ajoga** [awslabs/aws-service-catalog-factory#109]
# Context

I'm testing this project through the [workshop](https://service-catalog-tools-workshop.com/30-how-tos/50-every-day-use/180-adding-a-product-to-a-portfolio.html).

# Issue & step to reproduce

Once a portfolio has been defined in the CodeCommit repository for the factory, the build step of the `servicecatalog-factory-pipeline` pipeline instancies the `reinvent-cloud-engineering-governance-associations` CloudFormation stack. 

If an erroneous Portfolio Association is specified, the CloudFormation stack stays exists in a ROLLBACK_COMPLETE status and the build step return successfully. 

Subsequent attempts to fix the situation by fixing the Portfolio Association in the yaml file don't succeed : while the build step of the `servicecatalog-factory-pipeline` pipeline exits properly, the  `reinvent-cloud-engineering-governance-associations` CloudFormation stack isn't modified because its ROLLBACK_COMPLETE status makes that impossible.

# Current workaround

Deleting the `reinvent-cloud-engineering-governance-associations` CloudFormation stack and triggering the `servicecatalog-factory-pipeline` pipeline allows the build step of the `servicecatalog-factory-pipeline` pipeline to recreate a working CloudFormation stack to create the Portfolio Associations.

# Proposed modifications 

- Ensure the build fails if the `reinvent-cloud-engineering-governance-associations` CloudFormation stack can't reach the CREATE_COMPLETE status

**Comment by eamonnfaherty** [comment]
puppet supports the config option of should_delete_rollback_complete_stacks. adding that to factory would enable this

**Comment by eamonnfaherty** [comment]
+1 this ticket for the feature: https://github.com/awslabs/aws-service-catalog-factory/issues/304
