### ISSUE TITLE
Support for CFN Template > 51200 length

### ISSUE THREAD

**Issue by tv-17** [awslabs/aws-service-catalog-factory#111]
Currently facing this error on the validate stage of codepipeline

```
' at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200 
 
[Container] 2019/11/29 18:58:21 Command did not exit successfully aws cloudformation validate-template --template-body file://$(pwd)/product.template.yaml exit status 255 
[Container] 2019/11/29 18:58:21 Phase complete: BUILD State: FAILED 
[Container] 2019/11/29 18:58:21 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: aws cloudformation validate-template --template-body file://$(pwd)/product.template.yaml. Reason: exit status 255 
```

The upload of the template will work via the console both through the CloudFormation console and through Service Catalog, I believe this is due to the CloudFormation template being uploaded to an S3 bucket automatically. 

Couple of solutions which might work:
- Allow the possibility to disable aws cloudformation validate-template in the portfolio file 
- Provide a way to specify an s3 location in the portfolio file in conjunction with 
`aws cloudformation validate-template --template-url https://s3-.amazonaws.com/...../yourtemplate.json`

**Comment by jordan-evans** [comment]
Just hit this as well. I think ti would be good if Factory could do one of the following:

- Detect if the CFN Template is greater than 51200, and not run the `aws cloudformation validate-template` command
- Auto uploaded the template file to S3 and did the validation using the `--template-url` argument instead.

**Comment by eamonnfaherty** [comment]
resolved in https://github.com/awslabs/aws-service-catalog-factory/releases/tag/0.33.0
