### ISSUE TITLE
Upgrade instructions?

### ISSUE THREAD

**Issue by jlarrow** [awslabs/aws-service-catalog-factory#114]
I couldn't find information in the documentation about upgrading the version.

I currently have 0.31.0 deployed.  I've upgraded the CLI / Python part to 0.33.0 but how do I upgrade the resources in AWS?  Is it necessary to do this?

I looked at the diff between the two but I can't tell what lives where.

Is there a better place to ask questions like this?

Thanks!

**Comment by eamonnfaherty** [comment]
Hi,

There is a section in the docs on how to update:

https://aws-service-catalog-factory.readthedocs.io/en/latest/factory/upgrading.html

Please have a look through it and if you get stuck feel free to ask here for help.

BTW, asking questions here is fine - its currently the only place you can ask.

**Comment by jlarrow** [comment]
Thanks @eamonnfaherty.  I'm very sorry, I really don't know how I missed that page.  Everything is upgraded now.

**Comment by eamonnfaherty** [comment]
Please do not worry. I have made bigger mistakes.  Glad you are sorted now.
