### ISSUE TITLE
Use of 'aws/codebuild/standard:1.0' CodeBuild image causing elevated provisioning time

### ISSUE THREAD

**Issue by nathanroys** [awslabs/aws-service-catalog-factory#115]
As the `aws/codebuild/standard:1.0` image is now deprecated, AWS seems to no longer cache this image. This is causing provisioning times to be in the range of 3-4 minutes for CodeBuild projects.

The CodeBuild image should be set to the supported image `aws/codebuild/standard:3.0`.

**Comment by eamonnfaherty** [comment]
waiting for this to complete: https://travis-ci.org/awslabs/aws-service-catalog-factory/builds/640205365?utm_medium=notification
