### ISSUE TITLE
Support of the Json based product

### ISSUE THREAD

**Issue by KlodAyzak** [awslabs/aws-service-catalog-factory#118]
Hi, 
So far the product should be declared in yaml. It would be useful to also support json format as many predefined template a build in json. 
Doing that would shorten the time needed to build and deploy products

Brgds, 

Claude

**Comment by eamonnfaherty** [comment]
https://aws-service-catalog-factory.readthedocs.io/en/latest/factory/building_your_pipelines.html#using-json
