### ISSUE TITLE
Upgrade Issues

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-factory#121]
We're trying to upgrade from a fairly old version of Factory (0.15.0) to the newest release.

When running this through in our Test Environment we noticed that all the existing Factory Pipelines for our product / version combinations are re-run automatically.This means Factory re-deploys the respective versions for all our products into Service Catalog.

This is an issue because it then causes a knock-on effect when we run Service Catalog Puppet, as it thinks the deployed product needs to be updated when no changes are necessary. This causes a full deployment of products across out accounts for no reason (which we want to avoid). In some cases this taints deployed products, as the Stack Update will fail as most product templates are not actually modified.

I think we'd be fine with the upgrade if there was a way to stop the existing Factory pipelines from running automatically on the upgrade somehow?

**Comment by eamonnfaherty** [comment]
fixed in 0.36.0

**Comment by eamonnfaherty** [comment]
will be available when this build completes: https://travis-ci.org/awslabs/aws-service-catalog-factory/builds/652728076
