### ISSUE TITLE
Factory logs show failure but overall status is shown as success

### ISSUE THREAD

**Issue by smuralee** [awslabs/aws-service-catalog-factory#127]
* **Version**: 0.35.0
* **Issue**: The logs show a failure but the overall factory pipeline is marked as success
* **Steps to recreate**:
   * Create a new portfolio in the factory YAML
   * Add the component without "SupportDescription" tag
   * Run the factory pipeline

Stacktrace:

`

CreateProductTask failed
942 | parameters:
943 | description: CloudWatch insights for the Config API failures
944 | distributor: IT-Support-Customer
945 | name: cw-config-failures
946 | owner: central-it@customer.com
947 | region: us-east-2
948 | support_description: null
949 | support_email: central-it@customer.com
950 | support_url: https://wiki.customer.com/central-it-team/self-service/cw-config-failures
951 | tags:
952 | - <FrozenOrderedDict OrderedDict([('Key', 'product-type'), ('Value', 'cw-config-failures')])>
953 | uid: lz-demo-security-portfolio-cw-config-failures
954 |  
955 | Traceback (most recent call last):
956 |  
957 | File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run
958 | new_deps = self._run_get_new_deps()
959 |  
960 | File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 139, in _run_get_new_deps
961 | task_gen = self.task.run()
962 |  
963 | File "/usr/local/lib/python3.7/site-packages/servicecatalog_factory/luigi_tasks_and_targets.py", line 203, in run
964 | product_view_summary = aws.get_or_create_product(self.name, args, service_catalog)
965 |  
966 | File "/usr/local/lib/python3.7/site-packages/servicecatalog_factory/aws.py", line 71, in get_or_create_product
967 | **args
968 |  
969 | File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 276, in _api_call
970 | return self._make_api_call(operation_name, kwargs)
971 |  
972 | File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 559, in _make_api_call
973 | api_params, operation_model, context=request_context)
974 |  
975 | File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 607, in _convert_to_request_dict
976 | api_params, operation_model)
977 |  
978 | File "/usr/local/lib/python3.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
979 | raise ParamValidationError(report=report.generate_report())
980 |  
981 | botocore.exceptions.ParamValidationError: Parameter validation failed:
982 | Invalid type for parameter SupportDescription, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
983 |  
984 |  
985 |  
986 | [Container] 2020/02/18 16:31:14 Phase complete: BUILD State: SUCCEEDED
987 | [Container] 2020/02/18 16:31:14 Phase context status code:  Message:
988 | [Container] 2020/02/18 16:31:14 Entering phase POST_BUILD
989 | [Container] 2020/02/18 16:31:14 Phase complete: POST_BUILD State: SUCCEEDED
990 | [Container] 2020/02/18 16:31:14 Phase context status code:  Message:
991 | [Container] 2020/02/18 16:31:14 Expanding base directory path: .
992 | [Container] 2020/02/18 16:31:14 Assembling file list
993 | [Container] 2020/02/18 16:31:14 Expanding .
994 | [Container] 2020/02/18 16:31:14 Expanding file paths for base directory .
995 | [Container] 2020/02/18 16:31:14 Assembling file list
996 | [Container] 2020/02/18 16:31:14 Expanding results/*/*
997 | [Container] 2020/02/18 16:31:14 Expanding output/*/*
998 | [Container] 2020/02/18 16:31:14 Found 276 file(s)
999 | [Container] 2020/02/18 16:31:14 Phase complete: UPLOAD_ARTIFACTS State: SUCCEEDED
1000 | [Container] 2020/02/18 16:31:14 Phase context status code:  Message:
1001

`

**Comment by eamonnfaherty** [comment]
resolved in 0.37.0  waiting for release: https://travis-ci.org/awslabs/aws-service-catalog-factory/builds/652730398
