### ISSUE TITLE
Quote marks are stripped for String Numbers, e.g. Account Numbers, starting with 0.

### ISSUE THREAD

**Issue by sara-h-chen** [awslabs/aws-service-catalog-factory#128]
## Expected Behavior
SCFactory should package the product as is, and upload it to Service Catalog.

## Actual Behavior
SCFactory strips the quote marks, and this causes issues when this product is pushed to CloudFormation from Service Catalog, as CloudFormation parses strings beginning with 0s as octals.

## Steps to Reproduce the Problem
  1. Test using the following CFN template:

```
  TestParameter1:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /test/param
      Description: Foobar
      Type: String
      Value: '012345678910'

```
  2. Attempt to deploy the product through Service Catalog.
  3. The product will be uploaded to Service Catalog, looking like this:
```
  TestParameter1:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /test/param
      Description: Foobar
      Type: String
      Value: 012345678910
```
  4. When CFN deploys, the following SSM Parameter is created: 1.3376701607E10 
  
## Specifications
  - Version: 0.30.0

**Comment by eamonnfaherty** [comment]
Thanks for raising this.

I have tracked down what is causing this issue.

Within the framework we run a package command on all templates.  This enables us to handle templates that use local resources like AWS::Lambda::Function resources.  

Running the following command causes the issue you are describing to occur:

aws cloudformation package --template-file in-template.yaml --s3-bucket some-bucket --output-template-file out-template.yaml
