### ISSUE TITLE
Reduce number of product-version-specific pipelines

### ISSUE THREAD

**Issue by apreed** [awslabs/aws-service-catalog-factory#131]
By default, Factory creates a new codepipeline for every version of every product. 
With a large number of products, this quickly exceeds the standard limits of Events Rules and Codepipeline Pipelines within an account, which are 300 in both cases. 
These limits, while soft limits, require approval from the AWS Service team and an internal business process to implement, suggesting they are significant to service management. 
Our TAM has requested we try not to increase these limits.

**Comment by apreed** [comment]
Having done some research, it looks like a limitation on codepipeline which prevents it from working on multiple branches. 
The only possible solution I can see without an enhancement to codepipeline is replacing the current source step with a lambda function, but this makes things quite complex.

**Comment by eamonnfaherty** [comment]
this has been implemented
