### ISSUE TITLE
Support github as alternate source code location

### ISSUE THREAD

**Issue by michael-dickinson-sainsburys** [awslabs/aws-service-catalog-factory#150]
As far as I can tell from the documentation, currently only AWS CodeCommit is supported as a version control system, but it would be good to be able to store the code in GitHub (and maybe others?) in order to avoid having to introduce additional systems when existing ones are already in place within an organisation.

**Comment by eamonnfaherty** [comment]
Hi Michael,

You can use Github as a source for the pipelines.  It is described in the docs: https://aws-service-catalog-factory.readthedocs.io/en/latest/factory/building_your_pipelines.html#using-github 

You cannot currently use Github for the source of the ServiceCatalogFactory repository.

**Comment by michael-dickinson-sainsburys** [comment]
Apologies for the lack of clarity. The intention was to be able to use GitHub as the ServiceCatalogFactory repository.

**Comment by eamonnfaherty** [comment]
Hey @michael-dickinson-sainsburys 

This is now supported and here are the docs: https://aws-service-catalog-factory.readthedocs.io/en/latest/factory/getting_up_and_running.html#using-github-com-for-your-servicecatalogfactory-repo

I am hoping to make the puppet change this week also.

Eamonn

**Comment by michael-dickinson-sainsburys** [comment]
Awesome! Great news, thanks for adding this 👍
