### ISSUE TITLE
one general code repo instead of multiple product based repo's

### ISSUE THREAD

**Issue by costi1010** [awslabs/aws-service-catalog-factory#154]
Hi,

Is there any way to have one general product repo for products (and inside subfolders with various products/versions instead of each product having it's own code repo.
i.e 
 cloud-engineering 
    product A
      v1
      v2
     product B
      v1
In this way a central team can develop on one code repo simplifying a bit the setup.
What would be the recommendation here in the way of triggering the product pipelines hence they are triggered by codecommit . 

Thanx 
C

**Comment by eamonnfaherty** [comment]
Hi @costi1010 

mono repo support stage 1 has been released: https://github.com/awslabs/aws-service-catalog-factory/releases/tag/0.71.0 docs: https://service-catalog-tools-workshop.com/every-day-use/using-a-mono-repo.html
