### ISSUE TITLE
Add Build / Compile step before Validate in pipelines

### ISSUE THREAD

**Issue by shanesiebken** [awslabs/aws-service-catalog-factory#159]
We have several products that we define in (non cfn) code using SAM, Troposphere, "Serverless Framework", etc. The current Validate step "breaks" if we don't generate and commit our generated cfn code to our source repo (or provide an empty product.template.yaml, which invalidates validation). This is disruptive to our development workflow, as we expect to be able to build, validate, and deploy a template without having that ephemeral yaml permanently committed to our source.

A generic build or compile step (similar to Package, but prior to Validate) would allow us to perform whatever generation step we need to create the product.template.yaml for that validation step.

**Comment by shanesiebken** [comment]
This may serve to address issue #37 as well, depending on the expected behavior on that user's end.

**Comment by eamonnfaherty** [comment]
Resolved in https://github.com/awslabs/aws-service-catalog-factory/releases/tag/0.48.0
