### ISSUE TITLE
Add GitHub Enterprise support to CodePipeline

### ISSUE THREAD

**Issue by gabriele-l** [awslabs/aws-service-catalog-factory#160]
It would be very useful to have the generated CodePipeline to support GitHub Enterprise now that this feature is generally available.

https://aws.amazon.com/about-aws/whats-new/2020/09/aws-codepipeline-supports-github-enterprise-server/?nc1=h_ls

As of today I have to build synchronization jobs between GitHub Enterprise and CodeCommit.

GitHub Enterprise support will simplify a lot our infrastructure.

**Comment by eamonnfaherty** [comment]
this is now released (and for puppet)
