### ISSUE TITLE
Products being added to wrong portfolios

### ISSUE THREAD

**Issue by gergo-dryrun** [awslabs/aws-service-catalog-factory#168]
Hi,

I've installed version 0.48.2 of service catalog factory following the guide from https://service-catalog-tools-workshop.com/ to try out the changing the metadata of a portfolio/product feature.

Because I was also working on Service Catalog Puppet to try out the difference between product_generation_method import and copy I'm not sure at which point the issue started to happen.

The behaviour I'm experiencing is that products are being added to portfolios even without explicit association. And the CloudFormation template for the CodePipeline release also has the Deploy Configuration ProductId section updated.

I'm attaching my manifest.yaml, the product.template.yaml in every source repo has no meaningful content, just a mock AWS::CloudFormation::WaitConditionHandle resource.

Expected to see a one to one mapping between products and portfolios, but actual outcome is:

Product               |   Portfolios  | Status
------------ | ------------- |  -------------
aws-hello-world | dryrun-sample-applications | Correct
aws-hello-world-infra | dryrun-sample-applications, dryrun-sample-infra | 1 extra portfolio
aws-hello-world-infra-imported | dryrun-sample-applications, dryrun-sample-infra, dryrun-sample-infra-imported | 2 extra portfolios
aa-aws-hello-world-infra-imported | dryrun-sample-infra, dryrun-sample-infra-imported, dryrun-aa-sample-infra-imported | 2 extra portfolios

Additionally, the following CloudFormation generated templates have wrong ProductId added (It's the one from aws-hello-world-infra-v1 ): 
* aws-hello-world-infra-imported-v1
* aws-hello-world-infra-v1

I'm attaching the portfolio yaml. And maybe as hint, at one point I did rename some of the metadata for product aws-hello-world-infra, not sure if relevant.

[dryrun.yaml.zip](https://github.com/awslabs/aws-service-catalog-factory/files/5653317/dryrun.yaml.zip)

Thank you for looking into this, and if I can provide anything else of use, please let me know.

Cheers,
Gergo

**Comment by eamonnfaherty** [comment]
I have not been able to recreate this issue.  I have also looked through the code and I cannot see anything wrong.

Could you please try to recreate this issue.  You can renamed your portfolio yaml file to test it.

**Comment by gergo-dryrun** [comment]
Hi Eamonn,

Thank you for looking into this. I'll clean-up my setup and try from a fresh start.
