### ISSUE TITLE
Product version pushed to wrong product if the name is a subset

### ISSUE THREAD

**Issue by gergo-dryrun** [awslabs/aws-service-catalog-factory#173]
Hi,

We've identified a bug in the servicecatalog-factory present also in version 0.49.1 , similar to #168 . This time have created a reproducible setup.

Setup:
* In `ServiceCatalogFactory` have a portfolio `/portfolio/bug.yaml` defined with two products with names being sub/superset, such as : `simpleproduct` and `simpleproduct-suffxed`.
* Have version `v1` defined for each.

At this point we would have 2 CloudFormation stacks representing the version specific release pipelines:
* simpleproduct-suffixed-v1
* simpleproduct-v1

And inside the template each with the `Deploy` `Action` `Configuration` `ProductId` the relevant product ID from Service Catalog.

In `portfolio/bug.yaml` change the `Description` attribute of 'v1' version of `simpleproduct` product.

After the `servicecatalog-factory-pipeline` runs, **both** the CloudFormation stacks have the **same** `ProductId` defined, which is the one belonging to `simpleproduct-suffixed` product.

In addition, from this point on, if we try to define a `v2` for `simpleproduct` in the `/portfolio/bug.yaml` , the `simpleproduct-v2` pipeline will still have the  wrong`simpleproduct-suffixed` product ID and the version will be released under the wrong product.

This has the potential impact of also overriding existing product versions found in the `simpleproduct-suffixed`.

Attaching a zip with skeleton repository, git patch files and a README with command snippets to quickly reproduce.

Please let me know if there are any questions, looking forward to a fix, and guidance on how to correct the impacted products.

Best regards,
Gergo

[sc-factory-issue.zip](https://github.com/awslabs/aws-service-catalog-factory/files/6000617/sc-factory-issue.zip)

**Comment by eamonnfaherty** [comment]
Thanks for reporting this.  The detail in this submission has made it easy to reproduce.

**Comment by eamonnfaherty** [comment]
The deploy stage of the cfn template used to generate the pipeline is generated with the wrong product id in this above situation.  It has the correct description which means it is probably the mapping of products to ids where the defect is.

**Comment by eamonnfaherty** [comment]
Within the CreateProduct task there was a break statement with the incorrect level of indent.  This was causing an if statement to break and not the for loop.  This meant some variables were being overridden when they shouldn't have.

This should only have caused an issue when you create (or update) a product version where the name is a subset of a product that exists already and the AWS Service Catalog API returns the result set in a search as admin call in a specific order.

I have pushed out 0.49.2 which resolves this issue.

**Comment by peteawood** [comment]
This is still an issue, there was two levels of indent (i.e. two if statements) and the break is still happening at the outer if statement rather than the for loop. Not sure if I should be raising a new issue for this in case this comment doesn't get seen...

**Comment by peteawood** [comment]
Please ignore the above comment, details added to the closed https://github.com/awslabs/aws-service-catalog-factory/issues/222 issue
