### ISSUE TITLE
Tags defined in portfolio are applied incorrectly

### ISSUE THREAD

**Issue by michael-dickinson-sainsburys** [awslabs/aws-service-catalog-factory#189]
If you define a tag for a product with a value that is a reserved keyword in yaml you have to wrap it in quotes. However, this quoting is lost when the tags are applied in the cloudformation template. For example, adding a tag like this

```yaml
- Key: live
  Value: 'no'
```

results in the tag being applied in the cloudformation template as:
```yaml
- Key: live
  Value: no
```
which results in the value for the `live` key being set to `false` (instead of `no`) on the resource. I believe that this is due to `no` being a reserved word in YANL, and the fix is to quote the value in the cloudformation template, thus it would need the tag values to be wrapped in quotes in the jinja2 templates, e.g.:
```jinja2
{% for tag in tags %}
        - Key: {{ tag.get("Key") }}
          Value: "{{ tag.get("Value") }}"
{% endfor %}
```

**Comment by eamonnfaherty** [comment]
Thanks for reporting this @michael-dickinson-sainsburys  I will have a look at this tomorrow.

**Comment by eamonnfaherty** [comment]
Sorry for the delay on this. 

I checked through the code. It appears that the tags are being set correctly as strings at first glance. 

I will have a deeper dive into this first thing tomorrow morning.

**Comment by michael-dickinson-sainsburys** [comment]
No worries, was hoping to get to testing this out and working out a fix to contribute back but haven’t had a chance yet! I haven’t been able to test on the latest version of the tool, but the code appears to unquote the tags when it transfers them from the portfolio config file to the cfn template, which would result in the observed behaviour. I’ll try and get this tested on the most recent version tomorrow to check that it does the same thing still

**Comment by eamonnfaherty** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html#cfn-resource-tags-key and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html#cfn-resource-tags-value should both be strings so I am happy to add quotes around the values.

**Comment by eamonnfaherty** [comment]
0.58.0 contains this fix
