### ISSUE TITLE
unable to update product pipelines to include me-south-1 region

### ISSUE THREAD

**Issue by guyu-ye** [awslabs/aws-service-catalog-factory#197]
We added "me-south-1" as part of the enabled regions in the factory-initializer stack. When we released changes on servicecatalog-factory-pipeline in order to update product pipelines, we ran into the error below. Our home region is us-east-1. 

![image (2)](https://user-images.githubusercontent.com/86848027/124307149-03481900-db2d-11eb-9a4e-421fc8d29efc.png)

**Comment by eamonnfaherty** [comment]
this is resolved
