### ISSUE TITLE
Factory Validation for Stacks treats the "Active" parameter as a boolean

### ISSUE THREAD

**Issue by richardmilnerwatts** [awslabs/aws-service-catalog-factory#209]
Observed Behaviour:

The schema validation in Factory assumes that the Active parameter is boolean, in fact it should be a string:

  - Name: "myStack"
    Versions:
      - Name: "v1"
        Active: **True | terminated**
        Source:
          Provider: "S3"
          Configuration:
            BucketName: myBucket
            S3ObjectKey: "key.zip"

If a version is terminated, then Factory validation will fail.

Expected Behaviour:

I should be able to terminate a Stack version without validation failing.

**Comment by eamonnfaherty** [comment]
fixed in 0.66.0
