### ISSUE TITLE
customer provided tags for framework resources

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-factory#235]
Customers would like to provide their own tags for the resources created by the framework that are internal to the framework

**Comment by eamonnfaherty** [comment]
Logical Id |  Physical ID | Type | Stack parameters are inherited?
-- | -- | -- | -- | -- 
InitialiserProject | servicecatalog-product-factory-initialiser | AWS::CodeBuild::Project | ??
InitialiserRole | Initialiser | AWS::IAM::Role | ??
InitialiserVersionParam | service-catalog-factory-initialiser-version | AWS::SSM::Parameter | ??
StartInstall | - | Custom::CustomResource | ??
StartInstallLambda | foo-StartInstallLambda-lYmEylstYhtR | AWS::Lambda::Function | ??
StartInstallRole | StartFactoryInstallRole | AWS::IAM::Role | ??

**Comment by eamonnfaherty** [comment]
[] resources in the bootstrap and regional stacks do not inherit these tags

**Comment by mikeengland** [comment]
Hi @eamonnfaherty, is there a plan to support Tag Options so we can associate a Tag Options Library with a portfolio once Service Catalog Factory has published it? Thanks!

**Comment by eamonnfaherty** [comment]
Hi @mikeengland sorry I missed this message.  There are no plans at the moment to support tag options.  If you would like to see it added could you please raise a github issue for it and I can take a look.

**Comment by mikeengland** [comment]
Hi @eamonnfaherty, thanks for the reply. No worries - now I have learnt more about the service catalog, it makes sense to just attach the tag options separately to the catalog.
