### ISSUE TITLE
Validation Error using the latest version of SCT

### ISSUE THREAD

**Issue by manavyad** [awslabs/aws-service-catalog-factory#245]
**Stack Info:**
Initialiser template used to bring up the install ServiceCatalog-Factory {"version": "0.73.0", "framework": "servicecatalog-factory", "role": "initialiser"}

**Error Details:**
235  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/yamale/yamale.py", line 43, in validate
236    raise YamaleError(results)
237yamale.yamale_error.YamaleError: Error validating data with schema '/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/servicecatalog_factory/schema/schema-portfolios.yaml'
238    Products.0.Versions.0.Active: 'terminated' is not a bool.
239    Products.0.Source: Required field missing
240    Products.0.Versions.0.Active: 'terminated' is not a bool.
241
242[Container] 2021/09/21 10:36:42 Command did not exit successfully servicecatalog-factory --info validate . exit status 1
243[Container] 2021/09/21 10:36:42 Phase complete: BUILD State: FAILED
244[Container] 2021/09/21 10:36:42 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: servicecatalog-factory --info validate .. Reason: exit status 1

**codebuild stage:**
servicecatalog-product-factory-validate

![image (3)](https://user-images.githubusercontent.com/100514169/156618125-8304bc58-c76f-4716-b093-82a1da4236a2.png)

**Note:** Validation has been set to False/ Disabled for Factory in the stack

**Question:** Is it possible to rollback to an earlier version?

**Comment by eamonnfaherty** [comment]
This turned out to not be a defect.
