### ISSUE TITLE
Enhancement: Ability to externalise product definitions

### ISSUE THREAD

**Issue by robbrad** [awslabs/aws-service-catalog-factory#257]
As with the specification.yaml files in the Products/product-name/Versions/v1 and v2 etc folders for portfolio definition, it would be great if we could externalise the product definition to say Products/product-name/product-a.yaml

This would mean we could dynamically drop products into the products folder and have them automatically added to the portfolio.yaml just like with the versions

The folder structure would look like this - note the single product file in the product folder

<img width="608" alt="image" src="https://user-images.githubusercontent.com/6122503/168562451-e8cc19cf-fceb-431b-aea1-922bc17d77ec.png">

**Comment by eamonnfaherty** [comment]
released in 0.80.0
