### ISSUE TITLE
Failure when enabling ShouldValidate feature

### ISSUE THREAD

**Issue by manavyad** [awslabs/aws-service-catalog-factory#259]
We are currently running v0.79 of the SCT Factory and have had the ShouldValidate value set to false previously. As part of the update, we now want to use the Validation step in the SCT and have changed the ShouldValidate value to true, but get an error message as per below log when updating the SCT.

[sct factory validate failures.txt](https://github.com/awslabs/aws-service-catalog-factory/files/8707677/sct.factory.validate.failures.txt)

**Comment by eamonnfaherty** [comment]
can you share your portfolios/core.yaml file please.  It appears the portfolio you have declared may not be well formed.

**Comment by manavyad** [comment]
The file has been sent to the amazon email.

 

From: Eamonn Faherty ***@***.***>
Reply to: awslabs/aws-service-catalog-factory ***@***.***>
Date: Wednesday, 18 May 2022 at 09:37
To: awslabs/aws-service-catalog-factory ***@***.***>
Cc: "Yadav, Manav" ***@***.***>, Author ***@***.***>
Subject: Re: [awslabs/aws-service-catalog-factory] Failure when enabling ShouldValidate feature (Issue #259)

 

can you share your portfolios/core.yaml file please. It appears the portfolio you have declared may not be well formed.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>





Amazon Web Services EMEA SARL, 38 avenue John F. Kennedy, L-1855 Luxembourg, R.C.S. Luxembourg B186284

Amazon Web Services EMEA Sarl, UK Branch, 1 Principal Place, Worship Street, London, EC2A 2FA, United Kingdom, registered in England and Wales, UK Establishment No. BR019315

**Comment by eamonnfaherty** [comment]
these have been resolved.
