### ISSUE TITLE
Jinja2 no longer supported upstream dependancy broken: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by robbrad** [awslabs/aws-service-catalog-factory#265]
Please ensure you are using the latest version and have tried to run a validate command on your source files

# Steps to reproduce
1. Cloned latest source code
2. poetry install
3. Ran debug on generate.py

# Expected results
Debug runs

# Actual results
Exception has occurred: ImportError
cannot import name 'soft_unicode' from 'markupsafe'

See: https://github.com/pallets/markupsafe/issues/286#issuecomment-1044491026

**Comment by eamonnfaherty** [comment]
when you say ran debug on generate what do you mean? Are you running generate.py using a python debugger?

**Comment by eamonnfaherty** [comment]
are you using the correct version of python in your env? 

The following works for me:

git clone git@github.com:awslabs/aws-service-catalog-factory.git
cd aws-service-catalog-factory
poetry env use 3.7
poetry install
poetry run servicecatalog-factory validate path-to-ServiceCatalogFactory

**Comment by robbrad** [comment]
Must have been a dependancy issue at the time - did a fresh install of 0.82 and its fine now. 

Might be the upstream dependancy has been pinned (temporal issue)
