### ISSUE TITLE
SCFactory(0.84.0) creates both combined as well as individual version pipelines. Reopening generate-launch-constraints failure for latest version #273 

### ISSUE THREAD

**Issue by shydhanya** [awslabs/aws-service-catalog-factory#278]
Service Catalog Framework Multi-Region deployment failed using latest version #273 - Reopening as issue still exists

**Comment by shydhanya** [comment]
Version 0.84.0

SCFactory generates both combined pipelines as well as individual version pipelines. But the expected result is only combined pipelines for each product. 
Also, SCFactory fails in generate-launch-constraint deployment. 

# Issue1 : 

### Portfolio folder Structure: 
<img width="350" alt="image" src="https://user-images.githubusercontent.com/37020616/186256856-aab2c48f-68fe-4a0e-b813-04d28a09c627.png">

### Service Catalog Factory pipelines created multiple pipelines for each version as well as combined pipelines. 
<img width="560" alt="image" src="https://user-images.githubusercontent.com/37020616/186257070-b4e2c606-0285-4d29-ab8f-6c48da88fcc5.png">

# Issue2: 
ServiceCatalogFactory pipeline failed in generate-launch-contraints build. 
<img width="896" alt="image" src="https://user-images.githubusercontent.com/37020616/186257474-6a5dd80e-d643-4e99-9e5e-db771a8118da.png">

**Comment by eamonnfaherty** [comment]
fixed in 0.86.0
