### ISSUE TITLE
Member must have length less than or equal to 1000, Member must have length greater than or equal to 1

### ISSUE THREAD

**Issue by sandrich** [awslabs/aws-service-catalog-factory#279]
We are facing the following error when enabling multiple regions in factory. Reducing the amount of regions in the factory init template cures this error:

```
ERROR MainThread UPDATE_FAILED: ActionConfiguration Map value must satisfy constraint: [Member must have length less than or equal to 1000, Member must have length greater than or equal to 1] (Service: AWSCodePipeline; Status Code: 400; Error Code: ValidationException; Request ID: 5aed5280-3dd2-4f38-8780-c7488bb7e868; Proxy: null)
```

Tested on v. 0.83.0

**Comment by eamonnfaherty** [comment]
which type of pipeline was this on? I am assuming it was on products.

**Comment by eamonnfaherty** [comment]
Within the generic pipeline the Build stage EnvironmentVariables contains a variable named ALL_REGIONS which can cause the max length to be exceeded.

**Comment by eamonnfaherty** [comment]
pipeline_template_builder.py line 739 contains:

            dict(name="ALL_REGIONS", type="PLAINTEXT", value=" ".join(all_regions),),

This should be removed as an env var and instead the buildspec generated on line 800 in generate_build_spec should not use an env var for looping in shell - instead it should loop in python.

this change will need to be applied in at least two places.

**Comment by eamonnfaherty** [comment]
fixed in https://github.com/awslabs/aws-service-catalog-factory/releases/tag/0.87.0
