### ISSUE TITLE
StackTags?

### ISSUE THREAD

**Issue by MichaelReubenDev** [awslabs/aws-service-catalog-factory#281]
I'm trying to work out how I should tag CloudFormation Stacks as there seems to be no documentation on this. I have tried creating the following file in Factory called stacks.yaml

`
Schema: factory-2019-04-01
Stacks:

Name: tooling-spoke-roles
Versions:
Name: v1
Source:
Provider: "CodeCommit"
Configuration:
RepositoryName: "Tooling-Spoke-Roles"
BranchName: "v1"
Tags:
Key: "support_group"
Value: "AWS Cloud Platform"
Key: "application"
Value: "AWS Cloud Platform"
Key: "operating_company"
Value: "0600"
Key: "environment"
Value: "Production"
`
But Factory is failing with errors:
Include 'tag' has not been defined.
Include 'tag' has not been defined.
Include 'tag' has not been defined.
Include 'tag' has not been defined.
Stacks.0.Source: Required field missing
Include 'tag' has not been defined.
Include 'tag' has not been defined.
Include 'tag' has not been defined.
Include 'tag' has not been defined.

I don't know what I'm missing or doing wrong as I can only find the documentation for an example of how to create a stack which does not show any options for the tagging. It would be much easier if there was a documentation space for Factory and Puppet for all the options for Stacks and for Products.

**Comment by eamonnfaherty** [comment]
1) would you like to apply tags to the templates pushed into s3 by factory?

2) would you like to apply tags to the stacks provisioned by puppet? if so, i think adding tags to the manifest for a stack and a product would make a lot more sense than adding it in factory.  You could then apply different tags to the same template provisioned into different accounts using multiple launches/stacks.  If you would like this please raise an issue in the puppet repo.

**Comment by MichaelReubenDev** [comment]
To be honest I would be happy either way I think but I see your point on the fact that it's better to be able to tag on the deployment rather than on the product as it gives you more granularity. I can close this an I'll raise an issue in the puppet repo. Thanks :)
