### ISSUE TITLE
ServiceCatalog Multiple Secondary factory pipelines(version 0.87) failed to set SSM param

### ISSUE THREAD

**Issue by shydhanya** [awslabs/aws-service-catalog-factory#288]
ServiceCatalog Factory bootstrap-secondary cli failed to create a new factory pipeline. 

# Error Description 

`Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_ (Service: AmazonSSM; Status Code: 400; Error Code: ValidationException; `

# observation

Exception raised by create_or_update method.

**Comment by shydhanya** [comment]
I was able to safely delete individual product pipelines directly. Tested product update with Combined pipelines successfully. Note: Do not delete from CFN stack.

**Comment by eamonnfaherty** [comment]
fixed in https://github.com/awslabs/aws-service-catalog-factory/releases/tag/0.87.1

**Comment by shydhanya** [comment]
Thankyou Eamonn.

**Comment by vasindran** [comment]
Hi Eamonn, how to remove this secondary pipelines? its kind of duplicates!
Sometimes the product getting failed to provision when this duplicate pipeline is running and updating the products. I feel the behaviour of product getting change because of this pipeline update.
