### ISSUE TITLE
Product Termination in Version 0.87.0

### ISSUE THREAD

**Issue by shydhanya** [awslabs/aws-service-catalog-factory#289]
Termination Issue: `Status: terminated` action in portfolio, removed cloudformation stack that created auto-generated pipeline for individual factory. But `products--<product name>-pipeline` which is created by Combined Pipeline Mode is not terminated. 

Also, actual products inside portfolios are not removed as well.

**Comment by eamonnfaherty** [comment]
the status: terminated now means pipelines will be deleted but the service catalog products and provisioning artefacts remain.

This is to keep consistency with stacks, apps and workspaces. To allow users to delete both the pipeline and the AWS Service Catalog products (and artefacts) I have added this ticket: https://github.com/awslabs/aws-service-catalog-factory/issues/302 which I hope to tackle in the next week or two.
