### ISSUE TITLE
Service catalog factory created duplicate pipelines after 0.87.0 version upgraded

### ISSUE THREAD

**Issue by vasindran** [awslabs/aws-service-catalog-factory#291]
Please ensure you are using the latest version and have tried to run a validate command on your source files
We have recently upgraded the factory version to 0.87 to provision the tags in stacks resources, but the upgrade went for longer run of factory pipeline, and finally its created duplicate pipelines for all the products for every version.
# Steps to reproduce
1. Upgraded factory stack to 0.87.0 (the previous version was 0.67) by initiating the stack by referring the latest URL
2. Factory pipeline started running and it took long run
3. After factory pipeline done, there are duplicate pipelines for every product name starts with "products--"

# Expected results

Factory stacks should be in completed state
# Actual results

Factory stack was completed in status, but it created duplicate pipeline for all the products.
So how to remove this secondary pipelines? its kind of duplicates!
Sometimes the product getting failed to provision when this duplicate pipeline is running and updating the products. I feel the behaviour of product getting change because of this pipeline update.

we have existing pipeline for the SC product, example "sharedguardrails-spoke-vpc-v1", after updated the latest factory version 0.87.0, we are seeing a duplicate pipeline for every products like "products--spoke-vpc-1", both running if there is any change in codecommit repo.

**Comment by eamonnfaherty** [comment]
the behaviour was reverted in https://github.com/awslabs/aws-service-catalog-factory/releases/tag/0.89.0
