### ISSUE TITLE
Tasks.py output method doesnt produce clean filenames

### ISSUE THREAD

**Issue by robbrad** [awslabs/aws-service-catalog-factory#293]
Please ensure you are using the latest version and have tried to run a validate command on your source files

Running for a standard reinvent.yaml portfolio
The framework would error with issues on the filename containing "| pipes"

# Steps to reproduce
1. Run for reinvent.yaml
2. Output dir error occurs

# Expected results
Process should succeed

**Comment by eamonnfaherty** [comment]
this is resolved in https://github.com/awslabs/aws-service-catalog-factory/releases/tag/0.89.0
