### ISSUE TITLE
Not able to update service catalog factory to latest version

### ISSUE THREAD

**Issue by pallanagaraju** [awslabs/aws-service-catalog-factory#305]
Please ensure you are using the latest version and have tried to run a validate command on your source files

# Steps to reproduce
1.  i am trying update service catalog factory to latest version from the URL https://service-catalog-tools.s3.eu-west-2.amazonaws.com/factory/latest/servicecatalog-factory-initialiser.template.yaml.

2.  The cloud formation stack "factory-initialization-stack" is failed at startinstall stage with the error below
    "Received response status [FAILED] from custom resource. Message returned: CloudWatch Log Stream: 2022/10/22/[$LATEST]0df990fb691c4bf38236bb17d096c4b5 (RequestId: f3268ad7-b5fe-475a-9f0c-f1ccec3c18dc)"
Please find the attached screen shot for your reference.
![image](https://user-images.githubusercontent.com/11852155/197352455-36fad1b6-c5af-4374-a414-a255eb4df69e.png)

1. 

# Expected results
The cloudformation stack should deployed with out any failures.

# Actual results

**Comment by eamonnfaherty** [comment]
This appears to have been a break in some transient dependencies. I have changed the template to fix this.

Thanks for reporting this.
