### ISSUE TITLE
Wrong S3 product deployment template domain in China partition

### ISSUE THREAD

**Issue by tabasku** [awslabs/aws-service-catalog-factory#307]
Service Catalog Factory has [fixed S3 domain](https://github.com/awslabs/aws-service-catalog-factory/blob/0.90.0/servicecatalog_factory/cloudformation_servicecatalog_deploy_action.py#L112) that should be updated according to AWS partition. For example in AWS China domain for S3 HTTPS URL is something like
https://sc-factory-artifacts-XXXXXX-cn-north-1.s3.cn-north-1.amazonaws.com.cn/xxx

This makes product deployment fail in AWS China

# Steps to reproduce
1. Deploy Service Catalog Factory in AWS China partition region cn-north-1
2. Define Portfolio and Product
3. Deployment fails with error ´Invalid templateBody. Please make sure that your template is valid´

# Expected results

Deployed product version from template that was built with Service Catalog pipeline

# Actual results

New product creation fails due wrong AWS S3 domain in China partition.

**Comment by eamonnfaherty** [comment]
thanks for reporting this. I will take a look at this on Monday.

**Comment by eamonnfaherty** [comment]
fixed in 0.93.0
