### ISSUE TITLE
Read Custom Buildspec from Product Repository

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-factory#31]
I'd prefer it if we could tell SCF to look at buildspec files in the Product Repo instead of defining them in-line in the SCF Manifest. 

Maybe have a toggle in the manifest along the lines of `load_buildspec_from_repo: true` to toggle this.

This would be for the Tests step, and it should still output the correct artefacts for the Package step to pick up.

**Comment by eamonnfaherty** [comment]
does this mean you would like to add an existing stage to the test phase or would you like to edit one of the existing stages?

Would you need to archive any artifacts for later use?

**Comment by jordan-evans** [comment]
Thanks for the response @eamonnfaherty, maybe this will help if I explain the use case first and we can take it from there 😄 

The use case for this is I'd like to be able to use a CloudFormation wrapper to commit to my product repository, for example [aws-cdk](https://github.com/awslabs/aws-cdk) or [troposphere](https://github.com/cloudtools/troposphere) instead of being forced to write native CloudFormation.

We can do this at the moment, but it requires us to generate the CloudFormation ourselves, and commit that to the repository alongside the "wrapper" code. Ideally I'd just like to commit the wrapper code, and have the Pipeline generate the end CloudFormation for us.

I guess this could be solved in one of 2 ways:

- Add additional steps into the Test stage to generate the CloudFormation before any tests are executed
- Add a custom Build stage into the Pipeline which will generate the CloudFormation, before passing it off to the existing Test & Package stages. (e.g. execute a `cdk synth`).

I guess the first approach would be easier, but maybe the second is cleaner? 

There shouldn't be any additional artefacts to archive. The idea is we'd still output a `product.template.yaml` file at the end of this for the existing Package stage to pick up as normal.

Thanks!

**Comment by eamonnfaherty** [comment]
thanks for the update @jordan-evans 

I have released a new version of factory that supports the external configuration of component versions.  This should help keep the size of the manifest manageable.  If you still get to the point where the file is getting too big again please open a new issue.

**Comment by eamonnfaherty** [comment]
I have created issues #35 #36 and #37 to capture the points here and we have released an update to help manage the size of the portfolio yaml so I am closing this.  If there are any other issues please raise them.
