### ISSUE TITLE
Package failure in products promotional pipeline with combinedMode enabled

### ISSUE THREAD

**Issue by shydhanya** [awslabs/aws-service-catalog-factory#314]
Upgrade SCT Factory to 0.94 and created a new portfolio with 3 versions of the product in Combined PipelineMode. 
Duplicate pipeline issue has been resolved and 3 actions in Source Stage w.r.t to each product version has been created successfully. 

# Expected results
Service Catalog Portfolio with 3 versions of a product is expected

# Actual results
Service Catalog Portfolio with 1 version of the product is generated. 

Products-- pipeline generated by factory failed while creating package for subsequent version. 
**Error Description:** 
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/37020616/202768158-24fe7e80-04ca-4e22-bc0b-3f5e6c3bd72b.png">

**Comment by shydhanya** [comment]
**SecondaryFactory Pipeline for CombinedMode products**. Detailed logs shared separately.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/37020616/206190565-53e15521-e713-4f0e-a907-466f33a117d3.png">

**Comment by eamonnfaherty** [comment]
Issue confirmed.  Hope to have a fix out today.

**Comment by eamonnfaherty** [comment]
this is resolved in https://github.com/awslabs/aws-service-catalog-factory/releases/tag/0.95.0 

Also, added extra support for /products so you can define tag options and launch role constraints - this previously had to be done on the corresponding /portfolio entry
