### ISSUE TITLE
Product pipeline - Update & Termination Issues in 0.95

### ISSUE THREAD

**Issue by shydhanya** [awslabs/aws-service-catalog-factory#317]
Reopening:  Package failure in products promotional pipeline with combinedMode enabled #314 

# Steps to reproduce
1. Created a Product pipeline with Combined Mode enabled 
2. Product pipeline has multiple sources w.r.t to each of its versions
3. Update product version description or branch name.
4. Terminate specific product version 

# Expected results
1. Product pipeline is expected to run automatically and update or terminate product versions in AWS Service Catalog 

# Actual results
1. ~~Update test case -> Product pipeline was manually triggered to update versions. Automatic pipeline trigger didnt happen.~~ moved to #318
2. Terminate test case -> Product pipeline was manually triggered as automatic trigger didn't work. Product versions are not terminated in AWS Service Catalog.

**Comment by eamonnfaherty** [comment]
This is two defects.  Could you please try to report a single defect within a single issue.  I have created another issue here: https://github.com/awslabs/aws-service-catalog-factory/issues/318
