### ISSUE TITLE
Pipelinemode:combined is not working with portfolio structure (products outside of main portfolio file)

### ISSUE THREAD

**Issue by babu-selvam** [awslabs/aws-service-catalog-factory#322]
Please ensure you are using the latest version and have tried to run a validate command on your source files
Factory version upgraded from 0.84.0 to **0.95.0**
# Steps to reproduce
1. Upgrade factory version from 0.84.0 to **0.95.0**
2. Create portfolio and product outside of main portfolio folder structure

# Expected results
Single product pipeline with multiple versions to be created

# Actual results
Product pipeline was not generated

Note:
Priority: High
Reason: Blocking production release

**Comment by pspanwar** [comment]
Similar issue being faced in my project too. Upgraded factory to 0.95.0 from 0.88.0 version. Factory build job[[_**servicecatalog-product-factory-build**_] fails with below error. 

`
AssociateProductWithPortfolioTask failed
--
25 | parameters:
26 | create_portfolio_task_ref: create-portfolio-saas-lz-tenant-agent-saas-lz-tenant-agent-portfolio-ap-northeast-1
27 | create_product_task_ref: create-product-tenant-agent-ap-northeast-1
28 | dependencies_by_reference:
29 | - create-product-tenant-agent-ap-northeast-1
30 | - create-portfolio-saas-lz-tenant-agent-saas-lz-tenant-agent-portfolio-ap-northeast-1
31 | manifest_files_path: .
32 | region: ap-northeast-1
33 | task_reference: create-product-association-saas-lz-tenant-agent-saas-lz-tenant-agent-portfolio-tenant-agent-ap-northeast-1
34 |  
35 | Traceback (most recent call last):
36 |  
37 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_factory/waluigi/scheduler.py", line 174, in worker_task
38 | task.execute()
39 |  
40 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_factory/waluigi/tasks.py", line 126, in execute
41 | self.run()
42 |  
43 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_factory/workflow/portfolios/associate_product_with_portfolio_task.py", line 31, in run
44 | self.create_portfolio_task_ref
45 |  
46 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_factory/waluigi/tasks.py", line 87, in get_output_from_reference_dependency
47 | f = self.input().get("reference_dependencies").get(reference).open("r")
48 |  
49 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/luigi/task.py", line 645, in input
50 | return getpaths(self.requires())
51 |  
52 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_factory/waluigi/tasks.py", line 51, in requires
53 | return dict(reference_dependencies=self.dependencies_for_task_reference())
54 |  
55 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_factory/waluigi/tasks.py", line 71, in dependencies_for_task_reference
56 | dependency_by_reference
57 |  
58 | File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_factory/waluigi/tasks.py", line 56, in get_task_from_reference
59 | f"{self.manifest_files_path}/tasks/{utils.escape(task_reference)}.json", "r"
60 |  
61 | **FileNotFoundError: [Errno 2] No such file or directory: './tasks/create_portfolio_saas_lz_tenant_agent_saas_lz_tenant_agent_portfolio_ap_northeast_1.json'**
`

NOTE: I tested version(0.95.0) directly with fresh installation and it worked.

**Comment by eamonnfaherty** [comment]
Fixed in 

https://github.com/awslabs/aws-service-catalog-factory/releases/tag/0.97.0
