### ISSUE TITLE
[CFNNagProject] CFNNag failing with locale error for Unicode standard files.

### ISSUE THREAD

**Issue by pspanwar** [awslabs/aws-service-catalog-factory#325]
[*] Please ensure you are using the latest version and have tried to run a validate command on your source files
 - Yes the validate command is working for the source file.
 - CFN Nag are also checked locally on the template and its working ok.
<img width="743" alt="image" src="https://user-images.githubusercontent.com/104004881/214416703-7c88601c-a303-4694-aa68-0717e06a20e9.png">

# Steps to reproduce
1. Enabled CFNNag on one of the existing product manifest configuration using options `ShouldCFNNag: True.`
2. Checked the file format locally as UTF-8.
<img width="737" alt="image" src="https://user-images.githubusercontent.com/104004881/214415576-91864451-4514-43aa-9e56-7e67ce6bcef6.png">
3. Factory pipeline executed successfully adding an additional stage for the CFNNag on the product pipeline.
4. Ran the product pipeline which failed with below locale error.

<img width="902" alt="image" src="https://user-images.githubusercontent.com/104004881/214417276-f2172dc9-4ec2-416b-9228-bb75f8f19bd0.png">

# Expected results
There should be not be any locale error irrespective of the file format[_UTF8 or ASCII_] used the by developers and should be handled by the tool.
We can use below option export to set UTF as that's also backward compatible with ASCII charset @ https://github.com/awslabs/aws-service-catalog-factory/blob/c923b7b97b3e3e32a54fc42265b70465af1287e7/servicecatalog_factory/template_builder/shared_resources.py#L207

`
export RUBYOPT='-KU -E utf-8:utf-8'
`

# Actual results
CFNNag should work successfully but its failing with FATAL error.
`
FAIL FATAL
ArgumentError: invalid byte sequence in US-ASCII
`

**Comment by eamonnfaherty** [comment]
fixed
