### ISSUE TITLE
Update CodeBuild Containers used to aws/codebuild/standard:6.0

### ISSUE THREAD

**Issue by peteawood** [awslabs/aws-service-catalog-factory#330]
This is a mirror issue of awslabs/aws-service-catalog-puppet#648.

# Current situation
We have received notifications that both versions 4.0 and 5.0 of the Ubuntu standard Docker Image will be moved to unsupported status on March 30th. The images will still work but provisioning times will increase and the images will not receive any further updates.

# Proposed solution
Upgrade usage of 4.0 and 5.0 in the Factory repo to standard image version 6.0

Many thanks!

**Comment by RobBrazier** [comment]
I saw a follow-on email saying that the decision to move 5.0 to unsupported has since been cancelled
```
Hello,

AWS CodeBuild notified customers on March 2, 2023 that the Ubuntu 20.04 standard 5.0 image [1] will be deprecated on March 30, 2023. We have since revised the decision and will not be deprecating this image. You may continue using the image as it will continue to get future updates.

If you have any questions or concerns, please reach out to AWS Support [2].

[1] Platform: Ubuntu 20.04 - Image: aws/codebuild/standard:5.0 - Definition: ubuntu/standard/5.0
[2] https://aws.amazon.com/support

Sincerely,
Amazon Web Services
```

**Comment by eamonnfaherty** [comment]
as of https://github.com/awslabs/aws-service-catalog-factory/releases/tag/0.101.0 you can configure the image within the initialiser template.
