### ISSUE TITLE
PollForSourceChanges=True (default) for CodeCommit imposes limit on number of Pipelines 

### ISSUE THREAD

**Issue by RobBrazier** [awslabs/aws-service-catalog-factory#335]
Please ensure you are using the latest version and have tried to run a validate command on your source files

Unfortunately due to a different issue we are unable to upgrade past 0.88.0, which I'll raise another issue for, however I can see this is still present in latest

On our previous (ancient) version of 0.49.2, PollForSourceChanges defaulted to False, however since upgrading past 0.82.0, it seems to have been set to True by default.

It appears there is a hard limit of 500 (or at least I can't find the entry that says '500' in service quotas dashboard)

Error in CloudFormation for the pipeline stack: `Maximum number of pipelines using periodic source checks in account (500) exceeded. Switch to event-based change detection such as Amazon CloudWatch Events or webhooks to save this pipeline`

I was wondering if there was a reason for this switch (as it seems different to the configuration that's in the terraform code as well or if we could revert this back to the default of False

https://github.com/awslabs/aws-service-catalog-factory/blob/master/servicecatalog_factory/template_builder/pipeline/source.py#L33

I know this _is_ technically configurable, however this would require us to update hundreds of products and/or versions to set things back how they were before :( 

# Steps to reproduce
1. Configure > 500 service catalog product versions
1. Run servicecatalog-factory-pipeline
1. 

# Expected results
version pipeline creation continues greater than 500 products

# Actual results
pipeline stacks fail to create after 500 is reached.

**Comment by eamonnfaherty** [comment]
resolved in https://github.com/awslabs/aws-service-catalog-factory/releases/tag/0.101.0
