### ISSUE TITLE
Service-catalog-factory installation failed 

### ISSUE THREAD

**Issue by jdhakar1995** [awslabs/aws-service-catalog-factory#341]
Hi Team,

I have been following the steps mentioned [here](https://service-catalog-tools-workshop.com/installation/20-service-catalog-factory.html) in order to install the service-catalog-factory(**latest version 0.101.0**). But the cloud formation stack is getting failed with below error. The value I'm setting for the stack parameter **EnabledRegions** is **eu-central-1** or **eu-central-1, eu-west-1**.

![image](https://user-images.githubusercontent.com/50800854/235423432-e0928aa1-73cd-4c94-a374-537cd161119f.png)

Below is the error message in code build project **servicecatalog-product-factory-initialiser**-

![image](https://user-images.githubusercontent.com/50800854/235423618-0f3cabd6-7682-4aff-852c-2685cf4b93e4.png)

Please let me know what I'm missing here.

**Comment by jdhakar1995** [comment]
Hi Team,

I tried to install the older versions like 0.96.0, 0.98.0 and 0.100.0. This time the build project fails during execution of next command in buildspec. Below is the screenshot-

![image](https://user-images.githubusercontent.com/50800854/236118459-4e42a97a-25e1-4c5c-aaf8-39503482279b.png)

It seems the command servicecatalog-factory set-string-config-value code_build_project_environment_image ${CODE_BUILD_PROJECT_ENVIRONMENT_IMAGE} was newly added in latest version(0.101.0) in [#340](https://github.com/awslabs/aws-service-catalog-factory/pull/340) which is causing the issue.

**Comment by eamonnfaherty** [comment]
Sorry for the delay on this fix.

This has been fixed in the release: https://github.com/awslabs/aws-service-catalog-factory/releases/tag/0.101.1
