### ISSUE TITLE
(docs) use AWS_PROFILE instead of AWS_DEFAULT_PROFILE

### ISSUE THREAD

**Issue by HieronymusLex** [awslabs/aws-service-catalog-factory#45]
according to the CLI docs, https://docs.aws.amazon.com/cli/latest/topic/config-vars.html the AWS_PROFILE variable is the env var used for profile selection, AWS_DEFAULT_PROFILE works but is legacy. for consistency it would be better to advise to use AWS_PROFILE in the docs

**Comment by eamonnfaherty** [comment]
made the change to the docs
