### ISSUE TITLE
Duplicate products created

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-factory#49]
Since updating to the latest release I'm noticing that duplicate products are being created when we define new products. One of them is empty, with the default `-` version, and the other one has the first version we define, but none of the subsequent ones.

**Comment by eamonnfaherty** [comment]
0.1.37 has not addressed this.  Still trying to reproduce this one.

**Comment by eamonnfaherty** [comment]
fixed in 0.1.38
