### ISSUE TITLE
Product Pipelines not triggered from commits

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-factory#50]
Might be related to #47 

Since the update to turn off pipeline polling, our product pipelines aren't executing on commit anymore.

I suspect the CloudWatch Event Rules haven't been created (as this is done for you when configuring through the console, I suspect they need to be created separately through the API).

**Comment by eamonnfaherty** [comment]
Thanks for reporting this @jordan-evans 

It has been fixed in 0.1.37.
