### ISSUE TITLE
PuppetRole trust policy

### ISSUE THREAD

**Issue by ritesh** [awslabs/aws-service-catalog-factory#64]
## Issue
When I enroll a new account as a spoke in an existing organization, it provisions a role in the spoke account that allows two sets of principals to assume it:

- All principals in the master account
- All principals in the spoke account

## Description
The PuppetRole's permissions policy allows Administrator access (via managed policy) along with other permissions to accept portfolio shares. 

Two issues here:
- Anyone with sts:AssumeRole in a spoke account can assume this role. While allowing sts:AssumeRole for all roles is a red flag in itself, it is unfortunately used as a pattern for 'jump accounts' where a security auditor might log into one account using SAML and then switch roles to different accounts with ReadOnly roles. This role (since it is a named IAM role) could allow them to become Admin.
- The PuppetRole has managed Admin as a policy but also other policies attached to it. Wouldn't the Admin managed policy give them all the permissions that they need (since it allows all actions for all resources)? 

## Potential solutions
- Allow the PuppetRole to be assumed by a known set of principals (either service principals, or standard role) from the master account 
- Allow the PuppetRole to be assumed only by known principals in the spoke account. This is going to be tricky, since we may not know who these principals should be until they are provisioned. If the principal in the spoke account that can assume this is known (i.e. FooRole), someone else could create a  low privileged role with that name and then switch before service-catalog-factory has had a chance to create the role that can assume PuppetRole

**Comment by jordan-evans** [comment]
Might be missing something here, but why does a principal in the Spoke account require access to the PuppetRole? I thought only the Master account required permissions to assume it?

**Comment by ritesh** [comment]
Wrong repo! Moving this to [service-catalog-puppet](https://github.com/awslabs/aws-service-catalog-puppet/issues)
