### ISSUE TITLE
Extra tagging

### ISSUE THREAD

**Issue by jmflynn81** [awslabs/aws-service-catalog-factory#91]
Would it be possible to pick up the tags from the products defined in the portfolios and tag the Cloudwatch and CodeBuild resources which get created? Is it possible to also create tags for the factory itself so the s3 buckets can be tagged as well as the other factory resources?

**Comment by eamonnfaherty** [comment]
I have moved the request for Is it possible to also create tags for the factory itself so the s3 buckets can be tagged as well as the other factory resources? to another issue (#95)

**Comment by eamonnfaherty** [comment]
released in 0.32.0
