### ISSUE TITLE
Remove sc-factory-artifacts-* bucket lifecycle policy

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-factory#92]
The `sc-factory-artifacts-<account_id>-<region>` buckets have a lifecycle policy to delete files after 90 days.

This causes issues as Service Catalog uses this bucket to store the product files (like CF templates). Expiration means product versions stop working 90 days after creation.

The policy needs to be removed.

**Comment by eamonnfaherty** [comment]
This is now fixed in 0.24.0
