### ISSUE TITLE
Docs : missing begginer step ?

### ISSUE THREAD

**Issue by ajoga** [awslabs/aws-service-catalog-factory#96]
Hey, 

I'm just playing around so far, and it seems to me that we're missing something either in the doc or in the boostrap cfn. 

Arrived at the [cloning the repo](https://github.com/awslabs/aws-service-catalog-factory/blob/master/docs/source/factory/getting_up_and_running.rst#L62) part of the doc, I saw that no repo existed. I had to manually trigger the pipeline to get the codecommit repo created. 

Are we missing something to trigger the first build or a documentation step ? I can help with the latter :>

**Comment by eamonnfaherty** [comment]
Sorry, we are missing a step from the docs.  We are building out new docs in parallel.  Once they are ready we will replace a large part of the read the docs of both factory and puppet.

**Comment by eamonnfaherty** [comment]
fixed in https://github.com/awslabs/aws-service-catalog-factory/releases/tag/0.26.0

**Comment by eamonnfaherty** [comment]
Please feel free to look through for better install instructions: https://aws-samples.github.io/aws-service-catalog-tools-workshop/

**Comment by ajoga** [comment]
Oh, I guess that I'll see you in SEC331-R1 :-)
